### ISSUE TITLE
python import caffe failed

### ISSUE THREAD

**Issue by davidshen84** [willyd/caffe-builder#13]
I have successfully build everything you provided. *Or I guess so, since the build process exited without error, and I got a bunch of files in ./install/bin*. When I try to import `caffe` in python, I got something like:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "caffe\__init__.py", line 1, in <module>
        from .pycaffe import Net, SGDSolver
      File "caffe\pycaffe.py", line 13, in <module>
        from ._caffe import Net, SGDSolver
    ImportError: DLL load failed: ?????????

The `???` is literally question marks.

I have added the `./install/bin` into the `sys.path` variable. I cannot look into the `_cafee.pyd` file. So i don't know which DLL it is trying to load.

**Comment by willyd** [comment]
You are probably missing the openblas dlls. Just copy the libgcc, libgfortran, libopenblas and libquadmath dlls next to _caffe.pyd. Or use dependency walker to figure out what dlls could be missing.

**Comment by willyd** [comment]
As a side note. `sys.path` is only for python modules you need to modify `os.environ['PATH']` to alter the path used to find binary deps like DLLs.

**Comment by davidshen84** [comment]
Adding `..\\bin` to so.environ['PATH'] helped me importing caffe
successfully.

Thanks a lot!

On Tue, Sep 15, 2015 at 11:38 PM Guillaume Dumont <notifications@github.com>
wrote:

> As a side note. sys.path is only for python modules you need to modify
> os.environ['PATH'] to alter the path used to find binary deps like DLLs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willyd/caffe-builder/issues/13#issuecomment-140435325>
> .
>
-- 

Regards,
David

**Comment by stavBodik** [comment]
where is _caffe.pyd located I cant find it ?
