### ISSUE TITLE
Problem with LevelDB: Boost not found

### ISSUE THREAD

**Issue by vfdev-5** [willyd/caffe-builder#14]
After succesful CMake configuration, compiling the project, I get the following error:
[ 82%] Performing configure step for 'leveldb'
loading initial cache file C:/VFomin_folder/PISE_project/Caffe-willyd/build/leve
ldb-prefix/tmp/leveldb-cache.cmake
-- Looking for 64-bit boost libraries
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindBoost.cm
ake:1182 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:50 (find_package)

CMake Error: The following variables are used in this project, but they are set
to NOTFOUND.

**Comment by vfdev-5** [comment]
This is the solution (https://github.com/willyd/caffe-builder/issues/5) :

set(leveldb_CMAKE_ARGS 
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_DEBUG_POSTFIX=d
   ####################################################
    -DBOOST_ROOT=${CMAKE_INSTALL_PREFIX}
    -DBOOST_LIBRARYDIR=${CMAKE_INSTALL_PREFIX}/lib
    -DBOOST_INCLUDEDIR=${CMAKE_INSTALL_PREFIX}/include/boost-1_58
  ###################################################
    -DBoost_USE_STATIC_LIBS=ON
    -DBoost_USE_MULTITHREAD=ON
    -DBoost_USE_STATIC_RUNTIME=OFF   
    )

and similar for Caffe

set(Caffe_CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DBoost_USE_STATIC_LIBS=ON
    -DBoost_USE_MULTITHREAD=ON
    -DBoost_USE_STATIC_RUNTIME=OFF
###################################################
    -DBOOST_ROOT=${CMAKE_INSTALL_PREFIX}
    -DBOOST_LIBRARYDIR=${CMAKE_INSTALL_PREFIX}/lib
    -DBOOST_INCLUDEDIR=${CMAKE_INSTALL_PREFIX}/include/boost-1_58
###################################################
    -DOpenCV_STATIC:BOOL=ON
    -DBLAS:STRING=Open
	  -DPROTOBUF_SRC_ROOT_FOLDER:PATH=${CMAKE_INSTALL_PREFIX}
	  -DOpenCV_DIR:PATH=${CMAKE_INSTALL_PREFIX}
    )

**Comment by willyd** [comment]
Thanks for reporting. Indeed, the same thing happens when you have another Boost library installed see #5.
