### ISSUE TITLE
fatal link error: ZLIB_EXPORT_LIBRARIES.lib can not be found

### ISSUE THREAD

**Issue by classner** [willyd/caffe-builder#15]
Hi @willyd,

great work with this builder! :) I just wanted to try it out and unfortunately the build (repeatedly) fails for me with a the above linker error. It occurs when building HDF5. Do you have any hints on how to fix this? Can you reproduce it?

One quick important but unrelated question: you mention in the README.MD that this builds a static library on Windows. How did you fix the linking difficulties, i.e., that symbols are optimized out during the link process by the MSVC compiler? As to my knowledge, this has not been possible with the 'unmodified' caffe.

Best,
Christoph

**Comment by willyd** [comment]
Hi @classner,

Never had this problem with HDF5. 

* Do you have another ZLIB installed somewhere? 
* When you build HDF5 do you see something like: `Using custom FindZLIB module`?
* You can try to add some `message("ZLIB = ${ZLIB_LIBRARIES})"` to the HDF5 cmake files to see where HDF5 fails to use the proper ZLIB library. Look for code around a call to `find_package(ZLIB)`.

See [GenerateForceLinkSymbolsHeader.cmake](https://github.com/willyd/caffe/blob/visualstudio/cmake/GenerateForceLinkSymbolsHeader.cmake) for the explanation on how the "linker optimization" issue is dealt with. Also, you can refer to the origin [PR comment](https://github.com/BVLC/caffe/pull/2816) where I describe the process a little bit.

**Comment by classner** [comment]
Thanks for the fast and thorough response! :) I was able to diagnose this, and it was indeed a library that CMake erroneously included in the build, the HDF5 lib itself. The build runs perfectly now, so I will close this issue.

This is an elegant way to force the symbol inclusion! Great work!
