### ISSUE TITLE
HDF5 link was moved

### ISSUE THREAD

**Issue by stoyanovd** [willyd/caffe-builder#18]
Hi!

Link to download HDF5 was moved to another folder.
was
https://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.zip
and now goes to
https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.15-patch1/src/hdf5-1.8.15-patch1.zip

current directory now contains version 1.8.16...

**Comment by willyd** [comment]
Thanks for letting me know. I will look into this.
