### ISSUE TITLE
Build fails with missing 'pthread.h' in Caffe.vcxproj

### ISSUE THREAD

**Issue by jpsacha** [willyd/caffe-builder#19]
I am building using VS12 on Windows 7 following instructions in readme (after correction for #18). It goes for a while fine till it stop on error in `Caffe.vcxproj`. The actual error message is in 
`Caffe-prefix\src\Caffe-build\CMakeFiles\CMakeError.log`:

```
Determining if the include file pthread.h exists failed with the following output:

...

D:\build\Caffe-prefix\src\Caffe-build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 
   Cannot open include file: 'pthread.h': No such file or directory [D:\build\Caffe-prefix\src\Caffe-build\CMakeFiles\CMakeTmp\cmTC_12ae6.vcxproj]
```

Look that I need to add `pthreads` library somewhere. What is the proper way to to it?

**Comment by willyd** [comment]
Never seen that one. By VS12 you mean 2013 right? You should not need to add pthreads but use Win32 Threads instead. The threads in caffe are checked here:

https://github.com/willyd/caffe/blob/msvc/cmake/Dependencies.cmake

See cmake doc for FindThreads:

https://cmake.org/cmake/help/v3.3/module/FindThreads.html

**Comment by jpsacha** [comment]
Thanks for the hint. It let me eventually realize that I was looking not at the cause of the problem but the last reported error that was not important. 

Error above that one was 

```
Could not find PROTOBUF Compiler
```

Very similar to situation described in Issue #17, so I followed advise there. Had to edit `Caffe-prefix\src\Caffe-build\CMakeCache.txt` and add location for `PROTOBUF_PROTOC_EXECUTABLE` and `PROTOBUF_LIBRARY` that are located in `install/vsprojects/Release` of the build directory.

**Comment by yosider** [comment]
I followed [the instruction for using CMake](https://github.com/tensorflow/tensorflow/blob/816ecb7a342c25c19daa8b19627346e1fb38e56f/tensorflow/contrib/cmake/README.md) but I got the same problem...

**Comment by z-pc** [comment]
I have a same problem. Reason for this problem is I back up a caffe_old.proto in src/caffe/proto.
Then I move it, and the problem solved
