### ISSUE TITLE
Thanks! Matlab Question

### ISSUE THREAD

**Issue by echalom** [willyd/caffe-builder#2]
Willyd, thanks for the awesome contribution of caffe-builder. Worked smoothly for me!
I'd like to know if /how I can build a Matlab mex file. I noticed in your caffe branch there's
https://github.com/willyd/caffe/blob/master/matlab/%2Bcaffe/private/caffe_.cpp
but I don't think caffe-builder builds the mex file. What do I need to do for that?
Thanks!

**Comment by willyd** [comment]
@echalom Thank you for your interest. To be honest I did not have time (or need) to use the MATLAB interface. What platform/OS/Compiler are you building with?

**Comment by echalom** [comment]
I'm using Windows 7 with "Visual Studio 11 2012 Win64" compiler. I'm not so comfortable with cmake, but I thought changing the build/DownloadCache/caffe/CMakeLists.txt file, and changing caffe_option(BUILD_matlab "Build Matlab wrapper" OFF IF UNIX OR APPLE) to
caffe_option(BUILD_matlab "Build Matlab wrapper" ON)
would work, but I don't know how to rebuild without rebuilding from scratch (i.e. cmake -G "<generator>" ..\caffe-builder). Any pointers/tips are much appreciated!

**Comment by willyd** [comment]
Ok. The caffe-builder.sln configures and generates solution and project files for every project when you build it. If you want to rebuild a single project (say Caffe) you can:

* Open caffe-builder.sln and build the the Caffe project. This will try to build both debug and release version regardless of the configuration selected in the caffe-builder.sln
* Go to your build folder and look for Caffe-prefix\src\Caffe-build\Caffe.sln. Open this and build as usual.

As for the MATLAB interface: The CMakeLists.txt uses a custom build step calling the mex command with include directories and libraries to link to. Also note that there is a comment that mentions that building a static lib is not supported and this could be true for Windows too. You will have to modifiy this CMakeLists.txt so the build can go through on Windows. If you succeed I'd be willing to include this in the [PR #2816](https://github.com/BVLC/caffe/pull/2816) I submitted to Caffe master.

**Comment by echalom** [comment]
Ok, So I'll build caffe-builder.sln and Caffe-prefix\src\Caffe-build\Caffe.sln. Don't these get built when I run cmake --build .  ?
Or, do you mean I should build these two separately AFTER I modify the CMakeLists.txt file?

Also, as an aside, I successfully built https://github.com/niuzhiheng/caffe/blob/windows/build/MSVCmex/matcaffe.sln but the
https://github.com/niuzhiheng/caffe/blob/windows/matlab/caffe/matcaffe.cpp file there is different (older, I suspect) than the one on your branch. I'm not 100% sure, I followed his instructions, but I think I had to manually copy 4 or 5 .lib files from windows/bin to windows/matlab/caffe in order for that to work. I can tell you which ones if that would help with your automated cmake script.

I'll try your changes, (assuming I understood you correctly) and let you know how I did. Are there any specific changes I need to CMakeLists.txt other than the line I mentioned?
Thanks a bunch!

**Comment by willyd** [comment]
> Ok, So I'll build caffe-builder.sln and Caffe-prefix\src\Caffe-build\Caffe.sln. Don't these get built when I run cmake --build . ?
> Or, do you mean I should build these two separately AFTER I modify the CMakeLists.txt file?

Yes. But since you want to modify the CMakeLists.txt of Caffe you may want to build from the Caffe solution as it feels more natural.  Whenever you modify the CMakeLists.txt CMake will pick up your changes and regenerate the Caffe projects for you automatically. The Caffe.sln will exist if and only if you have built the caffe-builder.sln once. After that, it can be used independtly of caffe-builder.

> Also, as an aside, I successfully built https://github.com/niuzhiheng/caffe/blob/windows/build/MSVCmex/matcaffe.sln but the
> https://github.com/niuzhiheng/caffe/blob/windows/matlab/caffe/matcaffe.cpp file there is different (older, I suspect) than the one on your branch. I'm not 100% sure, I followed his instructions, but I think I had to manually copy 4 or 5 .lib files from windows/bin to windows/matlab/caffe in order for that to work. I can tell you which ones if that would help with your automated cmake script.

The @niuzhiheng fork uses a normal VS solution so that's why you need to copy the libs around so that they are found by VS. In my fork you should not have to copy libs but you will definitely have to modify the matlab CMakeLists.txt a little bit.


> Are there any specific changes I need to CMakeLists.txt other than the line I mentioned?

Yes you will need to modify the [matlab CMakeLists.txt](https://github.com/willyd/caffe/blob/master/matlab/CMakeLists.txt). Change the lines below:

```CMake
# Comment all this block or add AND NOT MSVC in the if clause
if(NOT BUILD_SHARED_LIBS AND build_using MATCHES Matlab)
  message(FATAL_ERROR "Matlab MEX interface (with default mex options file) can only be built if caffe is compiled as shared library. Please enable 'BUILD_SHARED_LIBS' in CMake. Aternativelly you can switch to Octave compiler.")
endif()
```

make sure that:

```CMake
if(build_using MATCHES "Matlab")
  set(libflags -lcaffe${CAffe_POSTFIX} ${libflags}) # Matlab R2014a complans for -Wl,--whole-archive

  caffe_fetch_and_set_proper_mexext(Matlab_caffe_mex)
  add_custom_command(OUTPUT ${Matlab_caffe_mex} COMMAND ${Matlab_mex}
      ARGS -output ${Matlab_caffe_mex} ${Matlab_srcs} ${cflags} ${link_folders} ${libflags}
      DEPENDS caffe COMMENT "Building Matlab interface: ${Matlab_caffe_mex}" VERBATIM)
  add_custom_target(matlab ALL DEPENDS ${Matlab_caffe_mex} SOURCES ${Matlab_srcs})

elseif(build_using MATCHES "Octave")
```

forwards the good flags, includes and libs to the mex executable by adding:

```CMake
message("${cflags}")
message("${link_folders}")
message("${libflags}")
```
before:
```CMake
add_custom_command(OUTPUT ${Matlab_caffe_mex} COMMAND ${Matlab_mex}
```
Hope this helps.

**Comment by echalom** [comment]
So, I modified CMakeLists.txt as suggested.
I Built caffe-builder.sln from within VS 2013
I Built Caffe-prefix\src\Caffe-build\Caffe.sln from within VS2013
I was suspicious that there was no Matlab directory in the soln, but proceeded anyway.

Here's the following message in the build window:
Could NOT find MatlabMex (missing:  Matlab_mex Matlab_mexext)
I have an environment variable MATLAB_DIR pointing to the root matlab directory,
C:\Program Files\Matlab\2015a
Also, under ***** Caffe configuration summary ******
It lists BUILD_matlab: ON under General: section, but Matlab: NO (in the Matlab subsection)

Do you have a suggestion for the error / reason why Matlab is not building?
Thanks

**Comment by willyd** [comment]
CMake did not find MATLAB. 

CMake provides a FindMatlab.cmake file in C:\Program Files (x86)\CMake\share\cmake-3.2\Modules that would be called by default when someone calls

```CMake
find_package(Matlab)
```

but for some reason Caffe relies on a custom [FindMatlabMex.cmake](https://github.com/willyd/caffe/blob/master/cmake/Modules/FindMatlabMex.cmake). It seems there is some support for Windows there but for some reason it did not find your installation of MATLAB. Looking at the file at line 37 it seems that they try to find mex.bat in `${__matlab_root}/bin/mex/mex.bat` but on my workplace install it seems to be located in the `bin` directory.

You need to change the FindMatlabMex.cmake so that Matlab is found and then modify the CMakeLists.txt as discussed earlier.

**Comment by willyd** [comment]
BTW, whenever you change something in CMake files you can build the ZERO_CHECK project to do the configure again. So you will quickly see if MATLAB was found or not.

If the above does not succeed you can try to defined several variables in CMake GUI so that CMake *thinks* it found MatlabMex. You will need to define at least:

Matlab_mex -> path the mex.bat
Matlab_mexext -> path the mexext.bat
MatlabMex_FOUND -> TRUE
MATLABMEX_FOUND -> TRUE

**Comment by echalom** [comment]
In which file do I define those 4 variables (I use a simple text editor), and where in the file? In
DownloadCache\caffe\matlab\CMakeLists.txt or another file?
Also, I'm using CMake 3.3 not sure if it has the same FindMatlab.cmake.
But I did notice that (I think?) it expects Matlab_ROOT_DIR system variable (not MATLAB_DIR).
How can I rebuild if I only modified a system variable? Do I build ZERO_CHECK from VS 2013?

**Comment by willyd** [comment]
In Caffe.cmake in the caffe-builder project change the `Caffe_CMAKE_ARGS` to:

```CMake
set(Caffe_CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DBoost_USE_STATIC_LIBS=ON
    -DBoost_USE_MULTITHREAD=ON
    -DBoost_USE_STATIC_RUNTIME=OFF
    -DOpenCV_STATIC:BOOL=ON
    -DBLAS:STRING=Open
	  -DPROTOBUF_SRC_ROOT_FOLDER:PATH=${CMAKE_INSTALL_PREFIX}
	  -DOpenCV_DIR:PATH=${CMAKE_INSTALL_PREFIX}
-DMatlab_mex:PATH=<path to mex.bat>
-DMatlab_mexext:PATH=<path to mexext.bat>
-DMatlabMex_FOUND:BOOL=ON
-DMATLABMEX_FOUND_FOUND:BOOL=ON
    )                       
```
then Build or Rebuild the Caffe project in caffe-builder.

**Comment by echalom** [comment]
Still no luck. I can't build caffe-builder.sln
I modified Caffe.cmake as suggested, specifically the 2 lines with matlab_mex and matlab_mexext are: 
-DMatlab_mex:PATH=C:/Program\ Files/MATLAB/R2015a/bin/mex.bat
-DMatlab_mexext:PATH=C:/Program\ Files/MATLAB/R2015a/bin/mexext.bat
If I used just the path, the error was command not found.

Now, the error is:
Unknown MEX argument '-l'.

In CMakeLists.txt I'm not sure if/where ${CAffe_POSTFIX} is defined and/or what we want it to be.
  set(libflags -lcaffe${CAffe_POSTFIX} ${libflags}) # Matlab R2014a complans for -Wl,--whole-archive

Also, Here's the output of the 3 messages we added to build\DownloadCache\caffe\matlab\CMakeLists.txt:
12>  -DBOOST_ALL_NO_LIB;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/DownloadCache/caffe/src;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/install/include/boost-1_58;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/install/src;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/Caffe-prefix/src/Caffe-build/include;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/install/include;-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.0/include;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/install/include/opencv;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/DownloadCache/caffe/include;-ID:/Users/echalom/Projects/CNN/caffe-builder-master/build/Caffe-prefix/src/Caffe-build
12>  -L$<TARGET_LINKER_FILE_DIR:caffe>;-L$<TARGET_LINKER_FILE_DIR:gflags-static>;-L$<TARGET_LINKER_FILE_DIR:glog>;-L$<TARGET_LINKER_FILE_DIR:hdf5_hl>;-L$<TARGET_LINKER_FILE_DIR:lmdb>;-L$<TARGET_LINKER_FILE_DIR:leveldb>;-L$<TARGET_LINKER_FILE_DIR:snappy_static>;-LC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.0/lib/x64;-L$<TARGET_LINKER_FILE_DIR:opencv_core>;-L$<TARGET_LINKER_FILE_DIR:opencv_highgui>;-L$<TARGET_LINKER_FILE_DIR:opencv_imgproc>;-L$<TARGET_LINKER_FILE_DIR:OpenBLAS>;-LD:/Users/echalom/Projects/CNN/caffe-builder-master/build/install/lib;-LD:/Users/echalom/Projects/CNN/caffe-builder-master/build/install/vsprojects/Release
12>  -lcaffe;-lgflags-static;-lglog;-lhdf5_hl;-llmdb;-lleveldb;-lsnappy_static;-l;-lopencv_core;-lopencv_highgui;-lopencv_imgproc;-lOpenBLAS;-lboost_system-vc120-mt-1_58;-lboost_thread-vc120-mt-1_58;-lprotobuf

I'm also wondering if we'll need to Matlab/R2015a/extern/lib or Matlab/R2015a/extern/include at some point, and if so where?
Thanks.

**Comment by echalom** [comment]
Also, not sure if/how these links might help. They describe MS VS settings to generate a .mex file from cpp source. http://stackoverflow.com/questions/16716821/how-to-build-mex-file-directly-in-visual-studio
http://personal.ie.cuhk.edu.hk/~xy012/others/cuda_mex_vs.html

**Comment by willyd** [comment]
@echalom 

The arguments passed to the mex command seem to have a lot of garbage in them. I doubt that all the `-L$` are supposed to be there. You also have a `-l` without any library specified:

> 12> -lcaffe;-lgflags-static;-lglog;-lhdf5_hl;-llmdb;-lleveldb;-lsnappy_static;**-l**;-lopencv_core;-lopencv_highgui;-lopencv_imgproc;-lOpenBLAS;-lboost_system-vc120-mt-1_58;-lboost_thread-vc120-mt-1_58;-lprotobu

This is probably the cause of this error:

> Now, the error is:
> Unknown MEX argument '-l'.

Also the library names used by CMake to are probably wrong. For example, the opencv libs should have the version number in them. This is mostly likely the fault of the [caffe_parse_linker_libs](https://github.com/BVLC/caffe/blob/b41dd872d8d7851ca39094a263d04d5e18d20e59/cmake/Utils.cmake) function that does not parse the libraries correctly. Some of the code in this function won't work with MSVC, for example `CMAKE_BUILD_TYPE` is never defined with a multi configuration generator like VS. 

About these links:
> Also, not sure if/how these links might help. They describe MS VS settings to generate a .mex file from cpp source. http://stackoverflow.com/questions/16716821/how-to-build-mex-file-directly-in-visual-studio
> http://personal.ie.cuhk.edu.hk/~xy012/others/cuda_mex_vs.html

If the CMake files are fixed you won't need this. However, since it seems to be hard (for someone without experience with CMake) to get this part of the build to work in CMake you might just want to use this method instead. In the end, all you need to do is a dll project that links to the good libraries and has the good include directories and C++ flags. If you want to to know what these values should look like, just open the properties of the caffe.bin project in the Caffe.sln and make another project following the method described in the link above.

**Comment by willyd** [comment]
@echalom I just realized that there is a much easier way to compile the matlab interface.

CMake 3.3 has a new FindMatlab.cmake that adds a new command `matlab_add_mex` that takes setting up a custom target and building a mex file. This would simplify the CMake code responsible for creating the mex file. 

To test this:

* Install CMake 3.3
* Add a `find_package(Matlab)` after the `find_package(MatlabMex)`. The `find_package(MatlabMex)` is not required anymore but leave it there for now. 
* Make sure that Matlab was found by checking `Matlab_FOUND`.
* Inside matlab/CMakeLists.txt comment all the code and add:

```CMake
# you may need to add an include_directorties command here but try without first
matlab_add_mex(NAME matlab
                            SRC "+caffe/private/_caffe.cpp" # maybe you need to add some other sources
                            OUTPUT_NAME _caffe # change the output name to _caffe.mexw64
                            LINK_TO caffe # cmake will take care of forwarding the correct transitive library dependencies to your mex file
                          )
```
I did not try this but it should be pretty straight forward to fix any error you have with this method. Let me know how it goes.

**Comment by echalom** [comment]
@willyd Thanks so much. The .mex compiled but did not run in Matlab.
One minor "manual" fix that I needed to add to the Configuration properties, is that I needed to add the matlab libraries libmat.lib, libmex.lib, libmx.lib all in MATLAB_ROOT\extern\lib\win64\microsoft.
And I fixed a typo -- the SRC should be caffe_.cpp not _caffe.cpp.

As an aside, I also manually made another project and build the .mex file (adding/finding the .lib, include directories, c++ flags, etc). Unfortunately, there too that mex file was created, but did not run.

The error was the same in both .mexw64 files:
<pre><code>Invalid MEX-file
'\build\Caffe-prefix\src\Caffe-build\matlab\Release\caffe.mexw64':
Invalid access to memory location.
</code></pre>
When I attach the debugger in VS 2013, I get the following:
<pre><code>First-chance exception at 0x000007FEFD6FADCD in MATLAB.exe: Microsoft C++ exception: jitCgFailedException at memory location 0x000000000402B5B0.
'MATLAB.exe' (Win32): Loaded 'D:\Users\echalom\Projects\CNN\caffe-builder-master\build\Caffe-prefix\src\Caffe-build\matlab\Release\caffe.mexw64'. Module was built without symbols.
'MATLAB.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cudart64_70.dll'. Module was built without symbols.
'MATLAB.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\curand64_70.dll'. Module was built without symbols.
'MATLAB.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cublas64_70.dll'. Module was built without symbols.</code></pre>

I'm not sure if the errors are related to static library vs dynamic library? 
The build from @niuzhiheng worked for me, but the caffe_.cpp+ is different, with fewer handles.
Of course he links with dlls instead of static libraries.

I'm also looking at [https://github.com/BVLC/caffe/issues/15] to see if there's any hints to solutions there as well, but it doesn't look like it yet?

Thanks again for all your help and efforts into this. Let me know if you get it working.

**Comment by willyd** [comment]
@echalom 

Nice to see that you made some progress. Maybe if you build Debug, you can get some more insight into what is going on? I will definitely let you know if I make the matlab part work.

**Comment by lunzueta** [comment]
@echalom I was able to build matcaffe (and then test it satisfactorily in Matlab R2014b) from this Caffe version [https://github.com/happynear/caffe-windows] from @happynear, as mentioned here [https://github.com/BVLC/caffe/issues/15]. I was able to build it for x64 (there are more solution platforms available) and for that I included the following Matlab-related paths and files in the VS solution properties (apart from the rest of required paths and dependencies):

Additional include directories: C:\Program Files\MATLAB\R2014b\extern\include
Additional library directories: C:\Program Files\MATLAB\R2014b\extern\lib\win64\microsoft
Additional dependencies: libmx.lib;libmex.lib;libmat.lib

I'd also suggest you to have a look how the matcaffe project looks like in that Caffe version (I mean the files that are included and so on).

I'm not sure how to do this in CMake in a good way as @willyd did with his version, but I hope this helps to achieve this goal.

**Comment by echalom** [comment]
Thanks for the pointer @lunzueta.
I downloaded and compiled branch from @happynear and I end up with a caffe_.mexw64 in the matlab\+caffe\private folder. But I don't know how to get it to run. BTW, I'm using Matlab R2015a

In @niuzhieng version I can access the handlers directly e.g. typing
caffe('get_init_key') and/or caffe('set_mode_gpu').

In this version, I can't access caffe_ directly, but When I type caffe. (with the period) and then tab, Matlab shows me all the class functions/methods.

If I try caffe.reset_all for example I get the following error:
<pre><code>
Invalid MEX-file
'.\caffe\matlab\+caffe\private\caffe_.mexw64':
The specified module could not be found.

Error in caffe.reset_all (line 5)
caffe_('reset');
</code></pre>

I added ./matlab to the path, but +caffe folder can't be added (possibly because of the plus sign?)
Same goes for +caffe/+test. Also when I view the folders in the folder view in Matlab and hover over the +caffe/private folder, it says private folders can't be on the path.

Am I supposed to copy or move or rename the caffe_.mexw64 file?
Any suggestions would be appreciated.

@willyd I apologize for inappropriately using your space here.

**Comment by lunzueta** [comment]
@echalom Once you compile matcaffe you should go to Matlab, add to the Matlab path all the subfolders contained in the "caffe-windows\matlab" folder and then start testing it, for example, with the  "classification_demo.m" file included in "caffe-windows\matlab\demo". You can easily follow the instructions there to test other images if you want. Hope this helps.

**Comment by happynear** [comment]
Many users have asked this question. Most of them haven't add the 3rdparty library folder to the environment variable PATH.Wrong Matlab version may also cause this problem. Someone may link with MATLAB 2014 library, but run in MATLAB 2015.If you still got this error, the best way is to use dependencywalker to check if all the dlls can be found.

**Comment by echalom** [comment]
@happynear That's it. Thanks! I saw the comment, but had forgotten to do it!

**Comment by willyd** [comment]
I have updated my fork with the latest caffe and fixed the matlab interface build (see branch msvc). @happynear I got part of the implementation from your repo thanks. You need to set the option BUILD_matlab=ON
