### ISSUE TITLE
Is CuDNN support enabled by default?

### ISSUE THREAD

**Issue by mrgloom** [willyd/caffe-builder#24]
Is CuDNN support enabled by default? How I can check if caffe compiled with CuDNN?

**Comment by willyd** [comment]
No since you need to be a registered NVIDIA developper to have access to cuDNN. You need to use the `msvc` branch of my caffe repo to use cuDNN. See https://github.com/willyd/caffe/blob/msvc/cmake/Cuda.cmake#L174 to have an idea on how to enable cuDNN, i.e. what CMake variables need to be set.
