### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by summerstay** [willyd/caffe-builder#26]
I have compiled this and see there is an examples directory. Just to test it out, can you tell me how to run the simplest example? i.e. "caffe test model=???"
Edit: I got it working. I followed the directions from here: https://github.com/BVLC/caffe/tree/master/examples/cifar10
and whenever it said to use a .sh file, I opened it in a text editor and followed the steps by hand.

**Comment by Kelvinson** [comment]
hi,buddy,I use the caffe-windows and come across the problem,too-I don't know how to run the .sh file. It promotes that wget not found, then I install the Cygwin because it can run the shell script on Windows,I got stuck in caffe on windows...
