### ISSUE TITLE
Can I get a copy of Prebuilt binaries for Windows Caffe

### ISSUE THREAD

**Issue by guoming0000** [willyd/caffe-builder#33]
Hello, I can't download the Prebuilt binaries for Windows Caffe(https://github.com/BVLC/caffe/tree/windows) in China. Could you send me a copy? (**Visual Studio 2015,CUDA 8.0, Python 2.7**  will be fine) My email :  i@brightguo.com

**Comment by willyd** [comment]
Sorry I can't. You will have to build from sources.
