### ISSUE TITLE
can't download file "libraries_v120_x64_py27_1.0.1.tar.bz2"

### ISSUE THREAD

**Issue by Erica-W** [willyd/caffe-builder#40]
Hello, I'm a chinese developer.
When exec build_win.cmd ,I can't download your file "libraries_v120_x64_py27_1.0.1.tar.bz2".
Could you give me another way to download it？
Or you can send me a email with attachment.That will be very helpful.
Thx!

btw:My email address is ericawu.studio@gmail.com

**Comment by willyd** [comment]
Sorry I can't. You can build from source:

1. Clone this repo
2. Execute the  	build_v120_x64.cmd script
3. Build caffe by providing the cache file to the command line. Add these flags to the normal command line `-DUSE_PREBUILT_DEPENDENCIES=0 -C caffe-builder-config.cmake`

**Comment by Erica-W** [comment]
thank you! I'll try it again.
