### ISSUE TITLE
url download for hdf5 package has changed

### ISSUE THREAD

**Issue by jurneo** [willyd/caffe-builder#43]
it looks like the url for downloading hdf5-1.8.16
has changed to 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/CMake-hdf5-1.8.16.zip'

**Comment by heurainbow** [comment]
Yes, I found this problem as well

**Comment by kontramind** [comment]
Has this been fixed?

**Comment by willyd** [comment]
Fixed since b7b52a5ba92c1d36e8c5c248c4fcedaa48f1c413.

**Comment by kontramind** [comment]
I'm trying to build libraries and for several of them check for URL_MD5 is failing.

**Comment by willyd** [comment]
Could be a firewall issue. I triggered a CI build to make sure. You can check the status of the build here: https://ci.appveyor.com/project/willyd/caffe-builder/branch/master

**Comment by kontramind** [comment]
will look into that thanks...
