### ISSUE TITLE
How to add support for python 3.6?

### ISSUE THREAD

**Issue by Coderx7** [willyd/caffe-builder#46]
Hello @willyd and thank you for your already great job on Caffe windows. 
Recently I thought of using pycaffe in Python3.6. 
Is there any technical reason you didn't use python3.6 and instead opted for pyton3.5? 
If I want to use python3.6 what should I do ? 
Thanks in advance

**Comment by willyd** [comment]
Not sure why I opted for 3.5 at the time, there is no specific reason that I can recall.

To use python 3.6 you will have to rebuild boost python with python 3.6. Having python 3.6 on path should be enough for cmake to use this version.

The easiest way would be to rebuild every dependency using caffe-builder and use the caffe-builder-config.cmake as a cache file as documented here: https://github.com/willyd/caffe-builder#using-the-built-libraries-in-your-project

As a side note, I started, some time ago, some work to port the dependency management to vcpkg to ease customization for every user. You can have a look at [that](https://github.com/Microsoft/vcpkg/issues/294#issuecomment-308298469) if you are interested. Any help on that matter would be greatly appreciated.

**Comment by Coderx7** [comment]
Thanks, I'll have a look,
By the way, having a simple visit to your branches, it seem to me it would be much more helpful if you could update your branches readmes, and give a description of what is complete and what is not and pretty much what is needed

**Comment by willyd** [comment]
@Coderx7 thanks for your constructive comments.

> By the way, having a quick simple look at your branches, it seemed to me it would be much more helpful if you could update your branches readmes, and give a description of what is complete and what is not and pretty much what is needed

Could you elaborate more on that? Are you talking about my caffe or caffe-builder branches? It is really hard to support every possible setup a developer might have and I have myself very limited time to dedicate to caffe-windows. 

What kind of information are you missing?

**Comment by Coderx7** [comment]
@willyd : I specifically meant `https://github.com/willyd/vcpkg/tree/caffe`: 
I need to know what is needed and see if I can, help in any way.  
by the way I do know what you mean and I really appreciate all the hard work you have put on caffe-windows specifically. 
Best Regards

**Comment by willyd** [comment]
@Coderx7 Thanks. Next time I work on the vcpkg port I will try to document better what is left to be done.

**Comment by Coderx7** [comment]
By the way I have added some batch files for the windows examples (downloading and running the examples), how do I submit a PR ( in case you think its a good idea) , Do I submit the whole branch or should I only submit the folders that I added some files to? 
[Here is the branch](https://github.com/Coderx7/Caffe_1.0_Windows)

**Comment by willyd** [comment]
The smaller the PR the easier it is for me to review it. So more smaller PRs is a better idea than a huge single one. No sure how to create a PR from a repo that was not forked using the Fork button though.

**Comment by Coderx7** [comment]
@willyd submitted a pr today :[here is the link ](https://github.com/BVLC/caffe/pull/5872), I had to remove my older MS based repository and then re-fork Caffe and then submit my pr. 
Please have a look.

**Comment by Coderx7** [comment]
@willyd : Hi, I created the libraires successfully and everything seem to work at least on my PC, however when I tried to use the built libraries on a system other than the one by which I built the libraries , it gives me linker errors pointing to the lib files in the caffe-builder-master build directory!
I am getting erros like  : 
![image](https://user-images.githubusercontent.com/5382892/46572956-54864680-c99b-11e8-8ed3-e71ca39f81e4.png)

Why is this happening? How can I get around this? 
by the way I have uploaded the libraries on my branch if you need a quick look, [here it is](https://github.com/Coderx7/Caffe_1.0_Windows)

Update:
I noticed under share/pkgconfig there is a zlib.pc file which is the file that contains these address:
```
prefix=D:/CodingStuff/caffe-builder-master/build_v140_x64/libraries
exec_prefix=D:/CodingStuff/caffe-builder-master/build_v140_x64/libraries
libdir=D:/CodingStuff/caffe-builder-master/build_v140_x64/libraries/lib
sharedlibdir=D:/CodingStuff/caffe-builder-master/build_v140_x64/libraries/lib
includedir=D:/CodingStuff/caffe-builder-master/build_v140_x64/libraries/include

Name: zlib
Description: zlib compression library
Version: 1.2.8

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lz
Cflags: -I${includedir}
```
The same file exists in your libraries as well, however, I have no idea why I'm facing such error!!


Any help is greatly appreciated

**Comment by Coderx7** [comment]
I just noticed the last command in i.e. :
```
cmd> cd myproject
cmd> mkdir build
cmd> cd build
cmd> cmake -G <generator name> -C %caffe_builder_root%\caffe-builder\build\libraries\caffe-build-config.cmake
```
I dont remember executing this part! is it the reason I'm facing such errors? Anyway, I tried to run this like : 
```
cmake -G "Visual Studio 14 2015" -C D:\CodingStuff\caffe-builder-master_\build_v140_x64_\libraries\caffe-builder-config.cmake
```
but faced a weird error : 

```
loading initial cache file D:\CodingStuff\caffe-builder-master_\build_v140_x64_\libraries\caffe-builder-config.cmake
CMake Error: The source directory "D:/CodingStuff/caffe-builder-master_/build_v140_x64_/libraries/caffe-builder-config.cmake" is a file, not a directory.
Specify --help for usage, or press the help button on the CMake GUI.
```

What am I missing here?

**Comment by willyd** [comment]
I suppose that some CMake target exposes it's dependency to the caffezlib library. Look for any reference to caffezlib in .cmake files generated by the dependencies. I tried to make the paths relative to the top level directory of the install of caffe-builder but I may have missed something somewhere.

**Comment by Coderx7** [comment]
@willyd : That was it !, the culprit was in the `hdf5-targets.cmake` . changed them to the relative path and bingo ;) 
God bless you man 😉

**Comment by mjiansun** [comment]
Hello @willyd @Coderx7, when i create libraires, i get this errors:
![image](https://user-images.githubusercontent.com/19528209/71975072-0fac2800-324e-11ea-811c-c2fd24b4446f.png)
My envs:  
win10  
python3.5(not anaconda)  
cuda10.0  
cudnn7  
vs2015  
Ninja v1.9.0  
So, how to solve the problem? Any help is greatly appreciated.
