### ISSUE TITLE
Library files structure

### ISSUE THREAD

**Issue by FabHan** [willyd/caffe-builder#8]
I wanted to build Caffe dependencies following this tutorial. I excluded caffe from the cmake build though because I wanted to manage the solution file manually.

After building into install, this is what I see.

![image](https://cloud.githubusercontent.com/assets/12666582/9550984/4ca69990-4d63-11e5-9a9e-b606a8171bea.png)

The dependency libraries are not put into one place. Most are put into the lib directory. However, some are not. For example, opencv lib files are in x64\vc12\staticlib; protobuf files are in vsprojects\debug and vsprojects\release. In addition, there are lots of unnecessary folders/files in install as well.

Can we make the files structure cleaner for easier management?

**Comment by willyd** [comment]
@FabHan The idea here is to install the packages the way cmake expect them to be. For example opencv installs the libraries in folders that are prefixed by $arch/$vc_version as you mentioned. If we move them around we will make it harder for CMake to find them. We will have to write a custom Find\<PackageName\>.cmake for every single package. In my opinion this is suboptimal. Currently I only need to define FInd\<PackageName\>.cmake files to override those of the caffe lib and or manage non standard cases.

That being said I am not completely satisfied with caffe-builder that much. I would like something closer to apt-get or homebrew. Currently it is hard to reuse a projects with caffe-builder. I would like to build OpenCV once and reuse it in caffe and other projects for example. I am working on such a tool as a side project but it is too early too be pusblished.
