### ISSUE TITLE
Build the newest Caffe with Multi-GPU support

### ISSUE THREAD

**Issue by gclong** [willyd/caffe-builder#9]
Hi @willyd , thanks indeed for your caffe-builder work. It saved me a lot of time on making caffe works in my Windows PC.

I noticed that the newest version of BVLC/Caffe now supports Multi-GPU computation. I was wondering if it is possible to build it with your caffe-builder.

I modified line 5 in **"caffe-builder/cmake/packages/Caffe.cmake"** from

*buildem_download_package(GIT_REPOSITORY "https://github.com/**willyd**/caffe.git"*

to 

*buildem_download_package(GIT_REPOSITORY "https://github.com/**BLVC**/caffe.git"*

However, it seems be not works. Could please kindly advise me about how to do it correctly?

Thanks!
Gucan

**Comment by willyd** [comment]
Hi @gucan-long . You need a caffe branch that has both my changes to support Windows and those of BLVC to support multi-gpu. In git lingo you need to fork either BLVC's or my caffe repository and apply the changes from the other repository:

One way of doing this would be:
```shell
# first clone your own caffe fork
git clone https://github.com/gucan-long/caffe.git caffe
cd caffe
# update to BLVC upstream
git remote add upstream https://github.com/BLVC/caffe.git
git fetch upstream
git checkout master
git merge upstream/master 
# add willyd's work as another remote
git remote add willyd https://github.com/willyd/caffe.git
git fetch willyd
# branch off BLVC master
git checkout -b multigpu
# merge in the changes from willyd's branch
git merge willyd/visualstudio
# resolve any conflicts
git add <resolved files>
git commit
git push origin
```
Then change the `GIT_REPOSITORY` to your own repo and the `GIT_TAG` to multigpu. Please note that I could be wrong in the above git commands. I did not test them, but you get the idea. You can refer to [github's documentation](https://help.github.com/articles/syncing-a-fork/) to know how to sync a fork.

Let me know if you succeed or not.

**Comment by gclong** [comment]
Hi @willyd , thank you very much for your detailed reply. 

I tried as you suggested, but failed. The problem lies in the new added file of caffe/src/caffe/util/signal_handler.cpp. In which the signal-related functions lack supports in Windows. If possible, could you please have a look at it and kindly give some further suggestions?

Many thanks!

**Comment by willyd** [comment]
Yeah I briefly mentioned a possible solution in the PR comments for Windows but did not have time to integrate this change in my fork.

**Comment by gclong** [comment]
Hi @willyd thanks for your reply. By "a possible solution in the PR comments", could you please give me a url of it? Maybe I could have a try.

**Comment by willyd** [comment]
Here is the PR link. My "potential solution" is very brief though: https://github.com/BVLC/caffe/pull/2253.

**Comment by happynear** [comment]
@willyd 
You may refer to my fixation https://github.com/happynear/caffe-windows/blob/master/src/caffe/util/signal_handler.cpp .
There is no SIGHUP in windows. However, I like the "snapshot whenever I want" feature. So I use SIGBREAK to replace SIGHUP.

**Comment by willyd** [comment]
@gclong My fork now was the latest changes integrated. See branc [msvc](https://github.com/willyd/caffe/tree/msvc)

**Comment by gclong** [comment]
Hi @willyd . That is great! Thank you so much!
